apiVersion: apps/v1
kind: Deployment

metadata:
  name: sudoku-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: sudoku-app

  template:
    metadata:
      labels:
        app: sudoku-app

    spec:
      containers:
        - name: sudoku-container

          image: kurvashivashankar/sudoku-app:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
