name: Sudoku CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/sudoku-app:${{ github.sha }} .

      # 4. Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/sudoku-app:${{ github.sha }}

      # 5. Connect to EC2 and deploy to Minikube
      - name: Deploy to EC2 Minikube
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            echo "Connected to EC2"

            echo "Checking Minikube..."
            minikube status

            echo "Checking Kubernetes..."
            kubectl get nodes

            echo "Going to application directory..."
            cd ~/Sudo

            echo "Applying Deployment..."
            kubectl apply -f deployment.yaml

            echo "Applying Service..."
            kubectl apply -f service.yaml

            echo "Updating Docker image..."
            kubectl set image deployment/sudoku-app \
              sudoku-container=${{ secrets.DOCKER_USERNAME }}/sudoku-app:${{ github.sha }}

            echo "Waiting for deployment..."
            kubectl rollout status deployment/sudoku-app --timeout=120s

            echo "Checking Pods..."
            kubectl get pods -o wide

            echo "Checking Service..."
            kubectl get svc sudoku-service
