apiVersion: apps/v1
kind: Deployment

metadata:
  name: shiva-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: shiva-app

  template:
    metadata:
      labels:
        app: shiva-app

    spec:
      containers:
        - name: shiva-container
          image: shiva5913/shiva:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
