name: Shiva CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  # ==========================================
  # BUILD AND PUSH DOCKER IMAGE
  # ==========================================

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/shiva:latest .

      - name: Push Image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/shiva:latest


  # ==========================================
  # DEPLOY TO MINIKUBE
  # ==========================================

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      # ======================================
      # START MINIKUBE
      # ======================================

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker


      # ======================================
      # CHECK MINIKUBE
      # ======================================

      - name: Check Minikube
        run: |
          minikube status
          kubectl get nodes


      # ======================================
      # PULL IMAGE FROM DOCKER HUB
      # ======================================

      - name: Pull Docker Image
        run: |
          docker pull \
            ${{ secrets.DOCKERHUB_USERNAME }}/shiva:latest


      # ======================================
      # LOAD IMAGE INTO MINIKUBE
      # ======================================

      - name: Load Image Into Minikube
        run: |
          minikube image load \
            ${{ secrets.DOCKERHUB_USERNAME }}/shiva:latest


      # ======================================
      # DEPLOY KUBERNETES
      # ======================================

      - name: Deploy Application
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml


      # ======================================
      # UPDATE IMAGE
      # ======================================

      - name: Update Image
        run: |
          kubectl set image deployment/shiva-app \
            shiva-container=${{ secrets.DOCKERHUB_USERNAME }}/shiva:latest


      # ======================================
      # WAIT FOR DEPLOYMENT
      # ======================================

      - name: Check Deployment
        run: |
          kubectl rollout status deployment/shiva-app \
            --timeout=120s


      # ======================================
      # CHECK PODS
      # ======================================

      - name: Check Pods
        run: |
          kubectl get pods -o wide


      # ======================================
      # CHECK SERVICE
      # ======================================

      - name: Check Service
        run: |
          kubectl get service shiva-service
